name: Module Builder

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Zip Files
              working-directory: ./dist
              run: zip -r ./module.zip ./*

            - name: Get Version
              shell: bash
              id: get-version
              run: echo "::set-output name=version::$(node ./.github/workflows/get-version.js)"
            
            - name: Create Release
              id: create-release
              uses: ncipollo/release-action@v1
              with:
                allowUpdate: true
                name: Release ${{ steps.get-version.outputs.version }}
                draft: false
                prerelease: false
                token: ${{secrets.GITHUB_TOKEN}}
                artifacts: './module.zip, ./module.json'
                tag: ${{ steps.get-version.outputs.version }}